# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: MoonISP RDP
    url: https://rdp.moonisp.dk
  - name: MoonISP Mail
    url: https://mail.moonisp.dk
  # - name: MoonISP Plex
  #  url: https://plex.moonisp.dk
  # - name: MoonISP RT
  #  url: https://rt01.moonisp.dk 
  - name: MoonISP Cards
    url: https://cards.moonisp.dk

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: git.moonisp.dk
  # baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime
  introTitle: "**MoonISP Uptime**"
  introMessage: This is the MoonISP uptime stats page.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
